#!/usr/bin/env python3
"""
Format a decision JSON file as markdown suitable for a PR description.

Usage: format-decision-for-pr.py <path-to-decision.json>

Output goes to stdout.
"""

from __future__ import annotations

import json
import pathlib
import sys


def format_finding(item: dict) -> str:
    parts = []
    for key in ("finding", "impact", "recommendation", "rationale"):
        value = item.get(key, "")
        parts.append(f"**{key.capitalize()}:** {value}")
    return "\n\n".join(parts)


def format_section(label: str, content) -> list[str]:
    """Return the lines of a single section (or [] if content is empty/missing)."""
    if content is None:
        return []
    lines = [f"## {label}", ""]
    if isinstance(content, list):
        if not content:
            lines.append("_(no findings)_")
            lines.append("")
            return lines
        for i, item in enumerate(content, 1):
            if len(content) > 1:
                lines.append(f"### Finding {i}")
                lines.append("")
            lines.append(format_finding(item))
            lines.append("")
        return lines
    if isinstance(content, dict):
        for k, v in content.items():
            if isinstance(v, list):
                if v:
                    lines.append(f"- **{k}:**")
                    for entry in v:
                        lines.append(f"  - `{entry}`")
                else:
                    lines.append(f"- **{k}:** _(empty)_")
            else:
                lines.append(f"- **{k}:** `{v}`")
        lines.append("")
        return lines
    # Fallback for strings or anything unexpected
    lines.append(str(content))
    lines.append("")
    return lines


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: format-decision-for-pr.py <path>", file=sys.stderr)
        return 2

    data = json.loads(pathlib.Path(sys.argv[1]).read_text())

    out: list[str] = []
    out.append(f"# {data.get('title', '(untitled decision)')}")
    out.append("")
    out.append(f"- **Decision ID:** `{data.get('decision-id', '')}`")
    out.append(f"- **Status:** `{data.get('status', '')}`")
    out.append("")
    out.append("## Narrative")
    out.append("")
    out.append(data.get("narrative", "_(no narrative)_"))
    out.append("")

    # Section order matches the decision-pipeline chain
    SECTIONS = [
        ("context-validation", "Context Validation"),
        ("architecture-review", "Architecture Review"),
        ("referential-integrity", "Referential Integrity"),
        ("strategy-alignment", "Strategy Alignment"),
        ("principles-alignment", "Principles Alignment"),
        ("proponent-analysis", "Proponent Analysis"),
        ("challenger-analysis", "Challenger Analysis"),
    ]
    for key, label in SECTIONS:
        if key in data:
            out.extend(format_section(label, data[key]))

    out.append("---")
    out.append("")
    out.append("_Auto-generated by the `update-pull-request` job of the Decisions Pipeline whenever it completes._")
    out.append("")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
