import { useEffect, useState, useRef, useId } from 'react'
import { useParams, Navigate, useLocation } from 'react-router-dom'
import { getDecision, githubAction } from '../lib/api'
import { decisionChangeFields } from '../lib/narrative'
import { buildScope } from '../lib/scope'
import { HISTORY_EVENT_STYLES, CHANGE_TYPE_STYLES } from '../lib/theme'
import ScopeChip from '../components/decisions/ScopeChip'
import ScopeSelector from '../components/decisions/ScopeSelector'
import RequirementsList from '../components/decisions/RequirementsList'
import Markdown from '../components/ui/Markdown'
import EmptyState from '../components/ui/EmptyState'
import Button from '../components/ui/Button'
import Spinner from '../components/ui/Spinner'
import JsonPreview from '../components/ui/JsonPreview'
import ActivityHistory from '../components/common/ActivityHistory'
import {
  CheckIcon,
  DecisionIcon,
  ArrowLeft,
  DisclosureChevron,
  EditIcon,
} from '../components/ui/icons'
import AutoGrowTextarea from '../components/ui/AutoGrowTextarea'
import usePageTitle from '../hooks/usePageTitle'
import useActiveSection from '../hooks/useActiveSection'
import usePersistedSet from '../hooks/usePersistedSet'
import { toggleInSet } from '../lib/collections'
import { formatDateTime } from '../lib/format'

// Marks a section whose content was generated by Claude. A blue→red gradient
// robot icon with a matching gradient label, designed to stand out.
const AI_SECTIONS = new Set(['recommendations', 'analysis', 'architecture-changes'])

function AiRobotIcon({ className = 'w-5 h-5' }) {
  const gid = useId()
  return (
    <svg viewBox="0 0 24 24" className={className} aria-hidden="true">
      <defs>
        <linearGradient id={gid} x1="0" y1="0" x2="24" y2="24" gradientUnits="userSpaceOnUse">
          <stop stopColor="#2563eb" />
          <stop offset="1" stopColor="#dc2626" />
        </linearGradient>
      </defs>
      <path d="M12 2.2v2.8" stroke={`url(#${gid})`} strokeWidth="2" strokeLinecap="round" />
      <circle cx="12" cy="2.2" r="1.4" fill={`url(#${gid})`} />
      <rect x="4" y="6" width="16" height="13" fill={`url(#${gid})`} />
      <circle cx="9.2" cy="12" r="1.6" fill="white" />
      <circle cx="14.8" cy="12" r="1.6" fill="white" />
      <rect x="9" y="15.6" width="6" height="1.7" fill="white" />
    </svg>
  )
}

function AiBadge() {
  return (
    <span className="inline-flex items-center gap-1.5 align-middle" title="Generated by Claude AI">
      <AiRobotIcon className="w-5 h-5" />
      <span className="text-[11px] font-bold uppercase tracking-wide bg-gradient-to-r from-blue-600 to-red-600 bg-clip-text text-transparent">
        AI-generated
      </span>
    </span>
  )
}

// ── Status progress bar ───────────────────────────────────────────────────────

const STATUS_STEPS = ['draft', 'proposed', 'accepted', 'staged', 'committed']
const STATUS_TERMINAL = { rejected: 'error' }

const STATUS_TOOLTIPS = {
  draft: 'The decision is being drafted. Not yet submitted for analysis.',
  proposed: 'Submitted for AI analysis. Findings are generated at this stage.',
  accepted: 'Reviewed and accepted. Ready to be staged for application.',
  staged: 'Architecture changes are being applied via a pull request.',
  committed: 'Merged to main. Architecture changes are live.',
  rejected: 'This decision has been rejected and will not proceed.',
}

// Blue → red gradient across the five steps (matches the AI/Claude colourway),
// interpolated from #2563eb to #dc2626.
const STEP_COLORS = ['#2563eb', '#5354ba', '#814589', '#ae3557', '#dc2626']

function StatusProgress({ status }) {
  const isTerminal = status in STATUS_TERMINAL
  const activeStep = STATUS_STEPS.indexOf(status)

  return (
    // Scrolls rather than squishing the 5 steps on narrow screens.
    <div className="mb-8 overflow-x-auto">
      <div className="flex items-center gap-0 min-w-[460px]">
        {STATUS_STEPS.map((step, i) => {
          const isPast = !isTerminal && i < activeStep
          const isCurrent = !isTerminal && i === activeStep
          const reached = isPast || isCurrent

          return (
            <div key={step} className="flex items-center flex-1 last:flex-none">
              <div className="flex flex-col items-center" title={STATUS_TOOLTIPS[step]}>
                <div
                  className={`w-7 h-7 flex items-center justify-center text-xs font-semibold cursor-default text-white ${
                    reached ? '' : 'bg-gray-100 !text-gray-500'
                  } ${isCurrent ? 'ring-2 ring-offset-1 ring-gray-200' : ''}`}
                  style={reached ? { backgroundColor: STEP_COLORS[i] } : undefined}
                >
                  {isPast ? <CheckIcon className="w-3.5 h-3.5" /> : i + 1}
                </div>
                <span
                  className={`mt-1 text-xs whitespace-nowrap capitalize ${isCurrent ? 'font-semibold' : 'text-gray-500'}`}
                  style={isCurrent ? { color: STEP_COLORS[i] } : undefined}
                >
                  {step}
                </span>
              </div>
              {i < STATUS_STEPS.length - 1 && (
                <div
                  className={`flex-1 h-px mx-2 mb-4 ${i < activeStep && !isTerminal ? '' : 'bg-gray-200'}`}
                  style={
                    i < activeStep && !isTerminal
                      ? {
                          backgroundImage: `linear-gradient(to right, ${STEP_COLORS[i]}, ${STEP_COLORS[i + 1]})`,
                        }
                      : undefined
                  }
                />
              )}
            </div>
          )
        })}
        {isTerminal && (
          <>
            <div className="h-px w-6 bg-gray-200 mx-2 mb-4" />
            <div className="flex flex-col items-center" title={STATUS_TOOLTIPS.rejected}>
              <div className="w-7 h-7 flex items-center justify-center text-xs font-semibold bg-error-50 text-error-700 ring-2 ring-error-200 cursor-default">
                !
              </div>
              <span className="mt-1 text-xs capitalize font-semibold text-error-700">{status}</span>
            </div>
          </>
        )}
      </div>
    </div>
  )
}

// ── Status transition actions ─────────────────────────────────────────────────

const REJECTION_REASONS = [
  {
    value: 'duplicate',
    label: 'Duplicate, a similar decision already exists or has been accepted',
  },
  { value: 'superseded', label: 'Superseded: replaced by a newer or broader decision' },
]

// Forward arrow used by "Propose"; check-arrow used by Accept / Stage / Commit.
function ProposeArrow() {
  return (
    <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
      <path d="M3 7h8M8 4l3 3-3 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
    </svg>
  )
}
function CheckArrow() {
  return (
    <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
      <path d="M2 7l3.5 3.5L12 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
    </svg>
  )
}

// Primary "advance to the next stage" action. Folds the lifecycle transitions
// into the shared Button vocabulary; each stage keeps its signature colour via
// the custom variant, and the spinner replaces the label while transitioning.
function ForwardButton({ transitioning, spinnerClass = 'text-white', children, ...props }) {
  return (
    <Button variant="custom" disabled={transitioning} {...props}>
      {transitioning ? <Spinner size="sm" className={spinnerClass} /> : children}
    </Button>
  )
}

// Inline rejection panel — shared by the draft and proposed stages.
function RejectPanel({ rejectReason, setRejectReason, transitioning, onConfirm, onCancel }) {
  return (
    <div className="bg-error-50 border-t border-error-200 px-5 py-4 flex items-end gap-3">
      <div className="flex-1">
        <span className="block text-xs font-semibold text-error-700 mb-1">
          Reason for rejection
        </span>
        <select
          value={rejectReason}
          onChange={(e) => setRejectReason(e.target.value)}
          className="w-full px-3 py-1.5 text-sm border border-error-300 bg-white focus:outline-none"
        >
          {REJECTION_REASONS.map((r) => (
            <option key={r.value} value={r.value}>
              {r.label}
            </option>
          ))}
        </select>
      </div>
      <Button
        variant="custom"
        disabled={transitioning}
        onClick={onConfirm}
        className="bg-error-600 hover:bg-error-700 text-white"
      >
        Confirm Rejection
      </Button>
      <Button variant="ghost" size="sm" onClick={onCancel}>
        Cancel
      </Button>
    </div>
  )
}

function StatusActions({ status, onTransition, transitioning, decision, versionId }) {
  const [rejectOpen, setRejectOpen] = useState(false)
  const [rejectReason, setRejectReason] = useState('duplicate')

  const rejectPanel = (
    <RejectPanel
      rejectReason={rejectReason}
      setRejectReason={setRejectReason}
      transitioning={transitioning}
      onConfirm={() => {
        setRejectOpen(false)
        onTransition('rejected', { 'rejection-reason': rejectReason })
      }}
      onCancel={() => setRejectOpen(false)}
    />
  )

  if (status === 'draft') {
    return (
      <div className="mb-6">
        <div className="flex items-center justify-between gap-4 bg-brand-50 px-5 py-4">
          <div>
            <p className="text-sm font-semibold text-brand-900">Ready to propose this decision?</p>
            <p className="text-xs text-brand-600 mt-0.5">
              Moving to Proposed submits it for analysis and opens a pull request.
            </p>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <Button
              variant="danger"
              size="sm"
              disabled={transitioning}
              onClick={() => setRejectOpen((r) => !r)}
            >
              Reject
            </Button>
            <ForwardButton
              transitioning={transitioning}
              onClick={() => onTransition('proposed')}
              className="bg-brand-600 hover:bg-brand-700 text-white"
            >
              Propose
              <ProposeArrow />
            </ForwardButton>
          </div>
        </div>
        {rejectOpen && rejectPanel}
      </div>
    )
  }

  if (status === 'proposed') {
    return (
      <div className="mb-6">
        <div className="flex items-center justify-between gap-4 bg-success-50 px-5 py-4">
          <div>
            <p className="text-sm font-semibold text-success-700">
              Accept, reject, or return this decision?
            </p>
            <p className="text-xs text-success-600 mt-0.5">
              Accepting approves the change, ready to be staged for application.
            </p>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <Button
              variant="secondary"
              size="sm"
              disabled={transitioning}
              onClick={() => onTransition('draft')}
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Back to Draft
            </Button>
            <Button
              variant="danger"
              size="sm"
              disabled={transitioning}
              onClick={() => setRejectOpen((r) => !r)}
            >
              Reject
            </Button>
            <ForwardButton
              transitioning={transitioning}
              onClick={() => onTransition('accepted')}
              className="bg-success-500 hover:bg-success-700 text-white"
            >
              Accept
              <CheckArrow />
            </ForwardButton>
          </div>
        </div>
        {rejectOpen && rejectPanel}
      </div>
    )
  }

  if (status === 'accepted') {
    return (
      <div className="flex items-center justify-between gap-4 bg-emerald-50 px-5 py-4 mb-6">
        <div>
          <p className="text-sm font-semibold text-emerald-800">
            Stage this decision for application?
          </p>
          <p className="text-xs text-emerald-600 mt-0.5">
            Staging applies the artefact changes on the decision branch and opens a pull request for
            review.
          </p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <Button
            variant="secondary"
            size="sm"
            disabled={transitioning}
            onClick={() => onTransition('proposed')}
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to Proposed
          </Button>
          <ForwardButton
            transitioning={transitioning}
            onClick={() => onTransition('staged')}
            className="bg-emerald-700 hover:bg-emerald-800 text-white"
          >
            Stage
            <CheckArrow />
          </ForwardButton>
        </div>
      </div>
    )
  }

  if (status === 'staged') {
    return (
      <div className="flex items-center justify-between gap-4 bg-gray-800 px-5 py-4 mb-6">
        <div>
          <p className="text-sm font-semibold text-white">Ready to commit?</p>
          <p className="text-xs text-gray-300 mt-0.5">
            Committing merges the pull request into main and closes the decision branch.
          </p>
        </div>
        <ForwardButton
          transitioning={transitioning}
          spinnerClass="text-gray-700"
          onClick={() => onTransition('committed', { prNumber: decision?.['pr-number'] })}
          className="flex-shrink-0 bg-white text-gray-900 font-semibold hover:bg-gray-100"
        >
          {`Commit to v${versionId}`}
          <CheckArrow />
        </ForwardButton>
      </div>
    )
  }

  return null
}

// ── Analysis table ────────────────────────────────────────────────────────────

// Findings render in four equal (25%) columns — uniform across all seven
// analysis tables. Accept/decline is toggled by clicking the row (a coloured
// left accent + tint shows the state); the analysis locks once Accepted.
function AnalysisTable({ rows, sectionKey, accepted, onAccept, saving, locked }) {
  if (!rows?.length) return <p className="text-sm text-gray-500">No findings recorded.</p>
  const toggle = (i, isAccepted) => {
    if (!locked) onAccept(sectionKey, i, isAccepted ? 'declined' : 'accepted')
  }
  return (
    <div className="border border-gray-200 overflow-x-auto">
      <table className="w-full min-w-[640px] text-sm table-fixed">
        <thead>
          <tr className="bg-gray-50 border-b border-gray-200">
            {['Finding', 'Impact', 'Recommendation', 'Rationale'].map((h) => (
              <th
                key={h}
                className="w-1/4 px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide"
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100">
          {rows.map((row, i) => {
            const key = `${sectionKey}-${i}`
            // Accept/decline state: local overrides first, then JSON field, default to accepted
            const state = accepted[key] ?? row.review ?? 'accepted'
            const isSaving = saving === key
            const isAccepted = state === 'accepted'
            return (
              <tr
                key={i}
                onClick={() => toggle(i, isAccepted)}
                onKeyDown={(e) => {
                  if (!locked && (e.key === 'Enter' || e.key === ' ')) {
                    e.preventDefault()
                    toggle(i, isAccepted)
                  }
                }}
                tabIndex={locked ? undefined : 0}
                role={locked ? undefined : 'button'}
                aria-pressed={!locked ? isAccepted : undefined}
                title={
                  locked
                    ? 'Analysis is locked once the decision is Accepted'
                    : `Click to ${isAccepted ? 'decline' : 'accept'} this finding`
                }
                className={`align-top border-l-4 ${isAccepted ? 'bg-success-50 border-success-400' : 'bg-error-50 border-error-400'} ${locked ? '' : 'cursor-pointer hover:brightness-[0.98]'} ${isSaving ? 'opacity-60' : ''}`}
              >
                <td className="px-3 py-2.5 text-gray-700 break-words">
                  {row.finding ? <Markdown>{row.finding}</Markdown> : '—'}
                </td>
                <td className="px-3 py-2.5 text-gray-700 break-words">
                  {row.impact ? <Markdown>{row.impact}</Markdown> : '—'}
                </td>
                <td className="px-3 py-2.5 text-gray-700 break-words">
                  {row.recommendation ? <Markdown>{row.recommendation}</Markdown> : '—'}
                </td>
                <td className="px-3 py-2.5 text-gray-700 break-words">
                  {row.rationale ? <Markdown>{row.rationale}</Markdown> : '—'}
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// ── Recommendations section (narrative-validation output, separate from Analysis) ─

function ReviewSection({ decision }) {
  const items = decision['recommendations']
  if (!items?.length) return null
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
          <CheckIcon className="w-4 h-4 mt-0.5 text-success-600 flex-shrink-0" />
          <Markdown className="min-w-0">{item.recommendation}</Markdown>
        </li>
      ))}
    </ul>
  )
}

// ── Analysis tabs (Untitled UI underline style) ───────────────────────────────

const ANALYSIS_SECTIONS = [
  { key: 'impact-assessment', label: 'Impact Assessment' },
  { key: 'referential-integrity', label: 'Referential Integrity' },
  { key: 'strategy-alignment', label: 'Strategy Alignment' },
  { key: 'principles-alignment', label: 'Principles Alignment' },
  { key: 'guardrails-alignment', label: 'Guardrails Alignment' },
  { key: 'proponent-analysis', label: 'Proponent Analysis' },
  { key: 'challenger-analysis', label: 'Challenger Analysis' },
]

// Architecture-change artefact IDs are prefixed by domain (BUS-, DAT-, …).
const CHANGE_DOMAINS = [
  { prefix: 'BUS', label: 'Business Architecture Changes' },
  { prefix: 'DAT', label: 'Data Architecture Changes' },
  { prefix: 'INT', label: 'Integration Architecture Changes' },
  { prefix: 'APP', label: 'Application Architecture Changes' },
  { prefix: 'SOL', label: 'Solution Architecture Changes' },
]
const changeDomainPrefix = (c) => (c['artefact-id'] ?? '').split('-')[0]

function ArchitectureChangeTable({ changes, indices, accepted, onAccept, saving, canReview }) {
  return (
    <div className="border border-gray-200 overflow-x-auto">
      <table className="w-full text-sm table-fixed">
        <thead>
          <tr className="bg-gray-50 border-b border-gray-200">
            <th className="w-1/4 px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Artefact
            </th>
            <th className="w-1/6 px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Change
            </th>
            <th className="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Description
            </th>
            <th className="w-32 px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Review
            </th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100">
          {changes.map((c, j) => {
            const i = indices[j]
            const key = `architecture-changes-${i}`
            const state = accepted[key] ?? c.review ?? 'accepted'
            const isAccepted = state === 'accepted'
            const isSaving = saving === key
            return (
              <tr key={i} className={`align-top ${isAccepted ? 'bg-success-50' : 'bg-error-50'}`}>
                <td className="px-3 py-2.5">
                  <span className="font-mono text-xs bg-gray-100 text-gray-700 px-1.5 py-0.5">
                    {c['artefact-id']}
                  </span>
                  <span className="text-xs text-gray-500 ml-1.5">{c['artefact-name']}</span>
                </td>
                <td className="px-3 py-2.5">
                  <span
                    className={`text-xs font-medium px-2 py-0.5 capitalize ${CHANGE_TYPE_STYLES[c['change-type']] ?? 'bg-gray-100 text-gray-600'}`}
                  >
                    {c['change-type']}
                  </span>
                </td>
                <td className="px-3 py-2.5 text-gray-700">
                  {c.description ? <Markdown>{c.description}</Markdown> : '—'}
                </td>
                <td className="px-3 py-2.5">
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() =>
                        canReview &&
                        onAccept('architecture-changes', i, isAccepted ? 'declined' : 'accepted')
                      }
                      disabled={isSaving || !canReview}
                      className={`relative inline-flex h-5 w-9 flex-shrink-0 items-center transition-colors disabled:opacity-50 disabled:cursor-not-allowed focus:outline-none ${isAccepted ? 'bg-success-500' : 'bg-gray-300'}`}
                      title={
                        canReview
                          ? ''
                          : 'Accept/decline is only available while the decision is Accepted'
                      }
                    >
                      <span
                        className={`inline-block h-4 w-4 bg-white transition-transform ${isAccepted ? 'translate-x-[18px]' : 'translate-x-[2px]'}`}
                      />
                    </button>
                    <span
                      className={`text-xs font-medium whitespace-nowrap ${isAccepted ? 'text-success-700' : 'text-error-700'}`}
                    >
                      {isSaving ? <Spinner size="sm" /> : isAccepted ? 'Accepted' : 'Declined'}
                    </span>
                  </div>
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

function ArchitectureChanges({ changes, accepted, onAccept, saving, canReview }) {
  if (!changes?.length) return null
  // Keep original indices so review writes target the right array element.
  const withIndex = changes.map((c, i) => ({ c, i }))
  const groups = CHANGE_DOMAINS.map((d) => ({
    ...d,
    items: withIndex.filter(({ c }) => changeDomainPrefix(c) === d.prefix),
  })).filter((d) => d.items.length)
  // Anything that doesn't match a known prefix falls into an "Other" group.
  const known = new Set(CHANGE_DOMAINS.map((d) => d.prefix))
  const other = withIndex.filter(({ c }) => !known.has(changeDomainPrefix(c)))
  if (other.length) groups.push({ prefix: 'OTHER', label: 'Other Changes', items: other })

  return (
    <div className="space-y-6">
      {groups.map((g) => (
        <div key={g.prefix}>
          <h3 className="text-base font-semibold text-gray-800 flex items-center gap-2 mb-3">
            {g.label}
            <span className="text-xs px-1.5 py-0.5 font-medium tabular-nums bg-gray-100 text-gray-600">
              {g.items.length}
            </span>
          </h3>
          <ArchitectureChangeTable
            changes={g.items.map((x) => x.c)}
            indices={g.items.map((x) => x.i)}
            accepted={accepted}
            onAccept={onAccept}
            saving={saving}
            canReview={canReview}
          />
        </div>
      ))}
    </div>
  )
}

const ANALYSIS_KEYS = ANALYSIS_SECTIONS.map((s) => s.key)

// ── History section ───────────────────────────────────────────────────────────

function HistorySection({ history }) {
  if (!history?.length) return null
  return (
    <div className="border border-gray-200 overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-gray-50 border-b border-gray-200">
            <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide w-48">
              Date / Time
            </th>
            <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide w-32">
              Event
            </th>
            <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Notes
            </th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100">
          {history.map((entry, i) => (
            <tr key={i} className="align-top">
              <td className="px-4 py-3 text-gray-500 font-mono text-xs whitespace-nowrap">
                {formatDateTime(entry.timestamp)}
              </td>
              <td className="px-4 py-3">
                <span
                  className={`text-xs font-medium px-2 py-0.5 capitalize ${HISTORY_EVENT_STYLES[entry.event] ?? 'bg-gray-100 text-gray-600'}`}
                >
                  {entry.event}
                </span>
              </td>
              <td className="px-4 py-3 text-gray-600 text-xs">{entry.notes || '—'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ── Contents nav (document-style, left rail) ──────────────────────────────────

// Compact empty placeholder — a small icon + message, used for "no findings
// yet" and unpopulated sections (smaller than the illustrated EmptyState).
function EmptyNote({ title, description }) {
  return (
    <div className="border border-dashed border-gray-200 bg-gray-50 px-4 py-4 text-center">
      <svg className="w-5 h-5 mx-auto mb-1.5 text-gray-300" viewBox="0 0 24 24" fill="none">
        <path
          d="M5 4h11l3 3v13H5z"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path d="M9 12h6M9 15h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
      <p className="text-sm font-medium text-gray-500">{title}</p>
      {description && (
        <p className="text-xs text-gray-500 mt-0.5 max-w-md mx-auto leading-relaxed">
          {description}
        </p>
      )}
    </div>
  )
}

// Inline editor for a Change field (Context / Problem / Proposal). Calls
// onChange with the raw string value. Used by DEC-5 inline editing.
function EditField({ value, onChange }) {
  return (
    <AutoGrowTextarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      minRows={3}
      className="w-full text-sm text-gray-700 leading-relaxed border border-gray-300 focus:border-brand-500 focus:outline-none px-3 py-2"
    />
  )
}

// Sub-keys grouped under the "Change" heading.
const CHANGE_SUB_KEYS = ['context', 'problem', 'proposal', 'narrative', 'scope', 'recommendations']

function buildNavSections(decision) {
  const hasSplit = decision.context || decision.problem || decision.proposal
  const changeSubs = hasSplit
    ? [
        { key: 'context', label: 'Context' },
        { key: 'problem', label: 'Problem' },
        { key: 'proposal', label: 'Proposal' },
      ]
    : [{ key: 'narrative', label: 'Narrative' }]
  changeSubs.push({ key: 'scope', label: 'Scope' })
  changeSubs.push({
    key: 'recommendations',
    label: 'Recommendations',
    count: decision['recommendations']?.length ?? 0,
  })

  const analysisTotal = ANALYSIS_SECTIONS.reduce((n, s) => n + (decision[s.key]?.length ?? 0), 0)

  return [
    { key: 'change', label: 'Change', subs: changeSubs },
    { key: 'requirements', label: 'Requirements', count: decision.requirements?.length ?? 0 },
    {
      key: 'analysis',
      label: 'Analysis',
      count: analysisTotal,
      subs: ANALYSIS_SECTIONS.map((s) => ({
        key: s.key,
        label: s.label,
        count: decision[s.key]?.length ?? 0,
      })),
    },
    decision['architecture-changes']?.length && {
      key: 'architecture-changes',
      label: 'Architecture Changes',
      count: decision['architecture-changes'].length,
    },
    decision.history?.length && {
      key: 'history',
      label: 'History',
      count: decision.history.length,
    },
  ].filter(Boolean)
}

function NavCount({ n, active }) {
  return (
    <span
      className={`text-xs px-1.5 py-0.5 font-medium tabular-nums flex-shrink-0 ${
        active
          ? 'bg-rose-100 text-rose-700'
          : n > 0
            ? 'bg-gray-100 text-gray-600'
            : 'bg-gray-50 text-gray-300'
      }`}
    >
      {n}
    </span>
  )
}

function ContentsNav({ sections, activeKey, onJump, onExpandAll, onCollapseAll }) {
  return (
    <aside className="hidden lg:block w-64 flex-shrink-0">
      <nav className="sticky top-20 max-h-[calc(100vh-6rem)] overflow-y-auto">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Contents</p>
          <div className="flex items-center gap-2">
            <button
              onClick={onExpandAll}
              className="text-xs text-gray-500 hover:text-gray-700 transition-colors"
            >
              Expand all
            </button>
            <span className="text-gray-300">·</span>
            <button
              onClick={onCollapseAll}
              className="text-xs text-gray-500 hover:text-gray-700 transition-colors"
            >
              Collapse all
            </button>
          </div>
        </div>
        <ul className="space-y-0.5">
          {sections.map((s, i) => (
            <li key={s.key}>
              <button
                onClick={() => onJump(s.key)}
                className={`w-full text-left text-sm px-3 py-1.5 transition-colors flex items-center gap-2 border-l-2 ${
                  activeKey === s.key
                    ? 'bg-rose-50 text-rose-700 border-rose-500 font-medium'
                    : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50 border-transparent'
                }`}
              >
                <span className="font-mono text-xs text-gray-500">{i + 1}</span>
                <span className="min-w-0 flex-1 truncate">{s.label}</span>
                {typeof s.count === 'number' && (
                  <NavCount n={s.count} active={activeKey === s.key} />
                )}
                {AI_SECTIONS.has(s.key) && <AiRobotIcon className="w-4 h-4 flex-shrink-0" />}
              </button>
              {s.subs && (
                <ul className="mt-0.5 space-y-0.5">
                  {s.subs.map((sub) => (
                    <li key={sub.key}>
                      <button
                        onClick={() => onJump(sub.key)}
                        className={`w-full text-left text-xs pl-9 pr-3 py-1 transition-colors flex items-center gap-2 border-l-2 ${
                          activeKey === sub.key
                            ? 'bg-rose-50 text-rose-700 border-rose-500 font-medium'
                            : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50 border-transparent'
                        }`}
                      >
                        <span className="min-w-0 flex-1 truncate">{sub.label}</span>
                        <NavCount n={sub.count} active={activeKey === sub.key} />
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </li>
          ))}
        </ul>
      </nav>
    </aside>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function DecisionDetailPage() {
  const { clientId, versionId, decisionId } = useParams()
  const location = useLocation()
  const [decision, setDecision] = useState(undefined)
  const [accepted, setAccepted] = useState({}) // local overrides for finding review state
  const [saving, setSaving] = useState(null) // key of the finding being saved, e.g. 'impact-assessment-0'
  const [transitioning, setTransitioning] = useState(false)
  const [transitionError, setTransitionError] = useState(null)
  const [pendingWorkflow, setPendingWorkflow] = useState(null) // { label } while a workflow populates the next section
  const [repoSlug, setRepoSlug] = useState(null) // owner/repo, for building a PR URL from pr-number
  const [edit, setEdit] = useState(null) // { title, context, problem, proposal } while inline-editing a draft
  const [savingEdit, setSavingEdit] = useState(false)

  useEffect(() => {
    fetch('/api/github?action=config')
      .then((r) => (r.ok ? r.json() : null))
      .then((c) => {
        if (c?.owner && c?.repo) setRepoSlug(`${c.owner}/${c.repo}`)
      })
      .catch(() => {})
  }, [])

  usePageTitle(decision?.title ? `${decision.title} · Decisions` : 'Decision')

  const sectionRefs = useRef({})
  const [activeSection] = useActiveSection(sectionRefs, [decision])
  const [collapsed, setCollapsed] = usePersistedSet(
    `decision-collapsed:${clientId}/${versionId}/${decisionId}`
  )
  const setSectionRef = (key) => (el) => {
    sectionRefs.current[key] = el
  }
  const toggleSection = (key) => setCollapsed((prev) => toggleInSet(prev, key))
  const scrollToSection = (key) => {
    setCollapsed((prev) => {
      const n = new Set(prev)
      n.delete(key)
      // Analysis sub-sections live under the collapsible 'analysis' parent
      if (ANALYSIS_KEYS.includes(key)) n.delete('analysis')
      if (CHANGE_SUB_KEYS.includes(key)) n.delete('change')
      return n
    })
    requestAnimationFrame(() =>
      requestAnimationFrame(() =>
        sectionRefs.current[key]?.scrollIntoView({ behavior: 'smooth', block: 'start' })
      )
    )
  }

  // Use branch-then-main fallback via getDecision helper.
  // Bust CDN cache if we just navigated back from the editor after a save.
  useEffect(() => {
    let cancelled = false
    const bust = !!location.state?.cacheBust
    getDecision(clientId, versionId, decisionId, undefined, { bust })
      .then((d) => !cancelled && setDecision(d))
      .catch(() => !cancelled && setDecision(null))
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId, versionId, decisionId])

  async function handleAccept(sectionKey, findingIndex, review) {
    const key = `${sectionKey}-${findingIndex}`
    const prev = accepted[key] // for rollback on failure
    // Optimistic update
    setAccepted((p) => {
      if (review === null) {
        const n = { ...p }
        delete n[key]
        return n
      }
      return { ...p, [key]: review }
    })
    setSaving(key)
    setTransitionError(null)
    try {
      await githubAction({
        action: 'update-finding',
        clientId,
        versionId,
        decisionId,
        sectionKey,
        findingIndex,
        review,
      })
    } catch (err) {
      // Roll back the optimistic change and surface the error.
      setAccepted((p) => {
        const n = { ...p }
        if (prev === undefined) delete n[key]
        else n[key] = prev
        return n
      })
      setTransitionError(`Couldn’t save the review: ${err.message}`)
    } finally {
      setSaving(null)
    }
  }

  async function handleTransition(newStatus, extraFields = {}) {
    setTransitioning(true)
    setTransitionError(null)
    const updates = { status: newStatus, ...extraFields }
    setDecision((prev) => (prev ? { ...prev, ...updates } : prev))
    try {
      const action = newStatus === 'committed' ? 'commit-decision' : 'update-decision'
      const body =
        action === 'commit-decision'
          ? { action, clientId, versionId, decisionId, prNumber: decision?.['pr-number'] }
          : { action, clientId, versionId, decisionId, updates }
      await githubAction(body)
      // These transitions dispatch a workflow that populates the next section
      // asynchronously — flag it so the UI shows a "working" banner.
      const WORKFLOW_LABELS = {
        proposed: 'running the seven analysis streams over your decision',
        accepted: 'working out the architecture changes',
        staged: 'applying the accepted changes and opening the pull request',
      }
      if (WORKFLOW_LABELS[newStatus]) setPendingWorkflow({ label: WORKFLOW_LABELS[newStatus] })
      // Re-fetch busting CDN cache so the new status is immediately visible
      getDecision(clientId, versionId, decisionId, newStatus, { bust: true })
        .then(setDecision)
        .catch(() => {})
    } catch (err) {
      setTransitionError(err.message)
    } finally {
      setTransitioning(false)
    }
  }

  function startEdit() {
    // Backfill legacy narrative-only decisions into the split fields (DEC-3).
    setEdit({
      title: decision.title ?? '',
      ...decisionChangeFields(decision),
      requirements: decision.requirements ?? [],
      scope: {
        domain: decision.scope?.domain ?? '',
        abstraction: decision.scope?.abstraction ?? '',
        artefact: decision.scope?.artefact ?? '',
      },
    })
  }

  // Save inline edits to a draft. edit-decision persists the fields and
  // re-dispatches decisions-to-draft, which refreshes the recommendations —
  // so we show the workflow banner. Only available while status === 'draft'.
  async function saveEdit() {
    const { requirements = [], scope: scopeSel, ...fields } = edit // fields: title/context/problem/proposal
    const scope = buildScope(scopeSel?.domain, scopeSel?.abstraction, scopeSel?.artefact)
    setSavingEdit(true)
    setTransitionError(null)
    setDecision((prev) =>
      prev ? { ...prev, ...fields, requirements, ...(scope ? { scope } : {}) } : prev
    ) // optimistic
    try {
      await githubAction({
        action: 'edit-decision',
        clientId,
        versionId,
        decisionId,
        ...fields,
        requirements: requirements.filter((r) => r.description?.trim()),
        scope,
      })
      setEdit(null)
      setPendingWorkflow({
        label: 'reviewing your updated narrative and refreshing recommendations',
      })
      getDecision(clientId, versionId, decisionId, undefined, { bust: true })
        .then(setDecision)
        .catch(() => {})
    } catch (err) {
      setTransitionError(err.message)
    } finally {
      setSavingEdit(false)
    }
  }

  if (decision === undefined) {
    return (
      <div className="flex items-center justify-center py-20">
        <Spinner size="lg" />
      </div>
    )
  }
  if (decision === null) {
    return <Navigate to={`/architectures/${clientId}/${versionId}/decisions`} replace />
  }

  const navSections = buildNavSections(decision)
  const sectionNumber = Object.fromEntries(navSections.map((s, i) => [s.key, i + 1]))
  const expandAll = () => setCollapsed(new Set())
  const collapseAll = () => setCollapsed(new Set(navSections.map((s) => s.key)))

  const renderSection = (key, children) => {
    const isCollapsed = collapsed.has(key)
    const navItem = navSections.find((s) => s.key === key)
    const label = navItem?.label ?? key
    const count = navItem?.count
    return (
      <section ref={setSectionRef(key)} data-section={key} className="scroll-mt-20">
        <button
          onClick={() => toggleSection(key)}
          className="w-full flex items-start gap-2 text-left group"
        >
          <span className="text-gray-300 group-hover:text-gray-500 mt-1.5">
            <DisclosureChevron open={!isCollapsed} />
          </span>
          <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2.5 flex-wrap">
            <span>
              <span className="text-gray-500 font-mono text-base mr-2">{sectionNumber[key]}</span>
              {label}
            </span>
            {typeof count === 'number' && (
              <span className="text-sm px-1.5 py-0.5 font-medium tabular-nums bg-gray-100 text-gray-600">
                {count}
              </span>
            )}
            {AI_SECTIONS.has(key) && <AiBadge />}
          </h2>
        </button>
        {!isCollapsed && <div className="mt-4 ml-6">{children}</div>}
      </section>
    )
  }

  // Analysis findings can only be accepted/declined while PROPOSED. Once the
  // decision is ACCEPTED (or later) the analysis is locked; architecture-change
  // review then opens up, and closes again once the decision leaves ACCEPTED.
  const analysisLocked = ['accepted', 'staged', 'committed', 'rejected'].includes(decision.status)
  const canReviewChanges = decision.status === 'accepted'

  // Collapsible H3 sub-section (used under Change and Analysis).
  const renderSub = (key, label, body, { count, hint } = {}) => {
    const subCollapsed = collapsed.has(key)
    return (
      <section key={key} ref={setSectionRef(key)} data-section={key} className="scroll-mt-20">
        <button
          onClick={() => toggleSection(key)}
          className="w-full flex items-center gap-2 text-left group"
        >
          <span className="text-gray-300 group-hover:text-gray-500">
            <DisclosureChevron open={!subCollapsed} />
          </span>
          <h3 className="text-base font-semibold text-gray-800 flex items-center gap-2">
            {label}
            {typeof count === 'number' && (
              <span className="text-xs px-1.5 py-0.5 font-medium tabular-nums bg-gray-100 text-gray-600">
                {count}
              </span>
            )}
            {hint && <span className="text-xs font-normal text-gray-500">· {hint}</span>}
          </h3>
        </button>
        {!subCollapsed && <div className="mt-3">{body}</div>}
      </section>
    )
  }

  const renderAnalysisSub = (s) => {
    const rows = decision[s.key] ?? []
    return renderSub(
      s.key,
      s.label,
      rows.length > 0 ? (
        <AnalysisTable
          rows={rows}
          sectionKey={s.key}
          accepted={accepted}
          onAccept={handleAccept}
          saving={saving}
          locked={analysisLocked}
        />
      ) : (
        <EmptyNote
          title="No findings yet"
          description="Populated when the analysis workflow runs, it can take a few minutes."
        />
      ),
      {
        count: rows.length,
        hint: !analysisLocked && rows.length > 0 ? 'click a row to accept / decline' : null,
      }
    )
  }

  return (
    <div>
      <div className="flex gap-8">
        {/* Contents nav: document-style left rail */}
        <ContentsNav
          sections={navSections}
          activeKey={activeSection}
          onJump={scrollToSection}
          onExpandAll={expandAll}
          onCollapseAll={collapseAll}
        />

        {/* Document surface */}
        <article className="flex-1 min-w-0 bg-white shadow-xl px-4 sm:px-8 py-6 sm:py-7">
          {/* Header */}
          <div className="mb-6 pb-5 border-b border-gray-200">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-red-600 flex items-center justify-center flex-shrink-0">
                <DecisionIcon className="w-5 h-5 text-white" />
              </div>
              <div className="flex-1 min-w-0">
                {edit ? (
                  <input
                    value={edit.title}
                    onChange={(e) => setEdit((p) => ({ ...p, title: e.target.value }))}
                    aria-label="Decision title"
                    className="w-full text-xl font-semibold text-gray-900 border-b border-gray-300 focus:border-brand-500 focus:outline-none pb-1"
                  />
                ) : (
                  <h1 className="text-xl font-semibold text-gray-900">{decision.title}</h1>
                )}
                {decision.scope && !edit && (
                  <div className="mt-2">
                    <ScopeChip scope={decision.scope} />
                  </div>
                )}
              </div>
              <div className="flex items-center gap-2 flex-shrink-0 self-start">
                <span className="text-xs font-mono bg-gray-100 text-gray-500 px-2 py-1">
                  {decision['decision-id']}
                </span>
                {decision['rejection-reason'] && (
                  <span className="text-xs text-gray-500">{decision['rejection-reason']}</span>
                )}
                {decision.status === 'draft' &&
                  (edit ? (
                    <>
                      <button
                        onClick={() => setEdit(null)}
                        disabled={savingEdit}
                        className="px-3 py-1 text-gray-500 hover:text-gray-900 text-xs font-medium transition-colors disabled:opacity-40"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={saveEdit}
                        disabled={savingEdit || !edit.title.trim()}
                        className="px-3 py-1 bg-brand-600 hover:bg-brand-700 text-white text-xs font-medium transition-colors disabled:opacity-40"
                      >
                        {savingEdit ? 'Saving…' : 'Save & re-review'}
                      </button>
                    </>
                  ) : (
                    <button
                      onClick={startEdit}
                      className="flex items-center gap-1.5 px-3 py-1 bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs font-medium transition-colors"
                    >
                      <EditIcon className="w-3.5 h-3.5" />
                      Edit
                    </button>
                  ))}
              </div>
            </div>
          </div>

          <StatusProgress status={decision.status} />

          {/* Status actions + any error: above the sections */}
          <div className="mb-2">
            <StatusActions
              status={decision.status}
              onTransition={handleTransition}
              transitioning={transitioning}
              decision={decision}
              versionId={versionId}
            />
            {transitionError && (
              <div className="px-4 py-3 bg-error-50 border border-error-300 text-error-700 text-sm">
                Failed to update: {transitionError}
              </div>
            )}
          </div>

          {/* Workflow-running banner: shown after a transition while the
              background workflow populates the next section. */}
          {pendingWorkflow && (
            <div className="mb-4 flex items-center gap-3 px-4 py-3 bg-gradient-to-r from-blue-50 to-rose-50 border border-blue-200 text-sm text-gray-700">
              <Spinner size="sm" />
              <span className="flex-1 min-w-0">
                🤖 The agents are {pendingWorkflow.label}. This usually takes a couple of minutes —
                grab a coffee, then check back.
              </span>
              <button
                onClick={() =>
                  getDecision(clientId, versionId, decisionId, undefined, { bust: true })
                    .then(setDecision)
                    .catch(() => {})
                }
                className="flex-shrink-0 px-3 py-1 text-xs font-medium text-blue-700 bg-white border border-blue-200 hover:bg-blue-50 transition-colors"
              >
                Check for updates
              </button>
              <button
                onClick={() => setPendingWorkflow(null)}
                className="flex-shrink-0 text-gray-500 hover:text-gray-700 transition-colors"
                title="Dismiss"
              >
                <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none">
                  <path
                    d="M4 4l8 8M12 4l-8 8"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                  />
                </svg>
              </button>
            </div>
          )}

          <div className="space-y-8">
            {/* Change: the proposal narrative, scope and recommendations */}
            {renderSection(
              'change',
              <div className="space-y-8">
                {edit || decision.context || decision.problem || decision.proposal ? (
                  <>
                    {renderSub(
                      'context',
                      'Context',
                      edit ? (
                        <EditField
                          value={edit.context}
                          onChange={(v) => setEdit((p) => ({ ...p, context: v }))}
                        />
                      ) : decision.context ? (
                        <Markdown className="text-sm text-gray-700 leading-relaxed">
                          {decision.context}
                        </Markdown>
                      ) : (
                        <EmptyNote title="Not provided" />
                      )
                    )}
                    {renderSub(
                      'problem',
                      'Problem',
                      edit ? (
                        <EditField
                          value={edit.problem}
                          onChange={(v) => setEdit((p) => ({ ...p, problem: v }))}
                        />
                      ) : decision.problem ? (
                        <Markdown className="text-sm text-gray-700 leading-relaxed">
                          {decision.problem}
                        </Markdown>
                      ) : (
                        <EmptyNote title="Not provided" />
                      )
                    )}
                    {renderSub(
                      'proposal',
                      'Proposal',
                      edit ? (
                        <EditField
                          value={edit.proposal}
                          onChange={(v) => setEdit((p) => ({ ...p, proposal: v }))}
                        />
                      ) : decision.proposal ? (
                        <Markdown className="text-sm text-gray-700 leading-relaxed">
                          {decision.proposal}
                        </Markdown>
                      ) : (
                        <EmptyNote title="Not provided" />
                      )
                    )}
                  </>
                ) : (
                  renderSub(
                    'narrative',
                    'Narrative',
                    <Markdown className="text-sm text-gray-700 leading-relaxed">
                      {decision.narrative}
                    </Markdown>
                  )
                )}
                {renderSub(
                  'scope',
                  'Scope',
                  edit ? (
                    <ScopeSelector
                      domain={edit.scope.domain}
                      abstraction={edit.scope.abstraction}
                      artefact={edit.scope.artefact}
                      onChange={({ domain, abstraction, artefact }) =>
                        setEdit((p) => ({ ...p, scope: { domain, abstraction, artefact } }))
                      }
                    />
                  ) : decision.scope ? (
                    <ScopeChip scope={decision.scope} />
                  ) : (
                    <EmptyNote
                      title="No scope set"
                      description="This decision applies to the whole architecture."
                    />
                  )
                )}
                {renderSub(
                  'recommendations',
                  'Recommendations',
                  decision['recommendations']?.length ? (
                    <ReviewSection decision={decision} />
                  ) : (
                    <EmptyNote
                      title="No findings yet"
                      description="Narrative Review runs when the decision is created and suggests improvements here."
                    />
                  ),
                  { count: decision['recommendations']?.length ?? 0 }
                )}
              </div>
            )}

            {renderSection(
              'requirements',
              edit ? (
                <RequirementsList
                  requirements={edit.requirements}
                  onChange={(r) => setEdit((p) => ({ ...p, requirements: r }))}
                />
              ) : decision.requirements?.length > 0 ? (
                <div className="border border-gray-200 divide-y divide-gray-100">
                  {decision.requirements.map((req, i) => {
                    const title = typeof req === 'string' ? null : req.title
                    const description = typeof req === 'string' ? req : req.description
                    const type = typeof req === 'object' ? req.type : null
                    return (
                      <div key={i} className="px-4 py-3">
                        <div className="flex items-center gap-2 mb-0.5">
                          {title && (
                            <span className="text-sm font-medium text-gray-900">{title}</span>
                          )}
                          {type && (
                            <span className="text-xs px-1.5 py-0.5 bg-gray-100 text-gray-500">
                              {type}
                            </span>
                          )}
                        </div>
                        <Markdown className="text-sm text-gray-600">{description}</Markdown>
                      </div>
                    )
                  })}
                </div>
              ) : (
                <EmptyNote
                  title="No requirements"
                  description="Use Edit to record what this decision must achieve."
                />
              )
            )}

            {renderSection(
              'analysis',
              <div className="space-y-8">{ANALYSIS_SECTIONS.map(renderAnalysisSub)}</div>
            )}

            {decision['architecture-changes']?.length > 0 &&
              renderSection(
                'architecture-changes',
                <ArchitectureChanges
                  changes={decision['architecture-changes']}
                  accepted={accepted}
                  onAccept={handleAccept}
                  saving={saving}
                  canReview={canReviewChanges}
                />
              )}

            {decision.history?.length > 0 &&
              renderSection('history', <HistorySection history={decision.history} />)}
          </div>

          {/* Status actions: repeated below the sections for convenience */}
          <div className="mt-8">
            <StatusActions
              status={decision.status}
              onTransition={handleTransition}
              transitioning={transitioning}
              decision={decision}
              versionId={versionId}
            />
          </div>
        </article>
      </div>

      {/* Activity sits outside the document surface (no white box / shadow) */}
      <ActivityHistory activity={decision.activity} />

      <JsonPreview
        data={decision}
        label={`${decision['decision-id']}.json`}
        prUrl={
          decision['pr-url'] ??
          (decision['pr-number']
            ? `https://github.com/${repoSlug ?? ''}/pull/${decision['pr-number']}`
            : null)
        }
      />
    </div>
  )
}
