import { useEffect, useState, useRef, useId } from 'react'
import { useParams, Navigate, useLocation, Link } from 'react-router-dom'
import { useArchitecture } from '../context/ArchitectureContext'
import { getDecision } from '../lib/api'
import { HISTORY_EVENT_STYLES, CHANGE_TYPE_STYLES } from '../lib/theme'
import ScopeChip from '../components/decisions/ScopeChip'
import Markdown from '../components/ui/Markdown'
import EmptyState from '../components/ui/EmptyState'
import Spinner from '../components/ui/Spinner'
import JsonPreview from '../components/ui/JsonPreview'
import ActivityHistory from '../components/common/ActivityHistory'
import { CheckIcon, DecisionIcon, ArrowLeft } from '../components/ui/icons'
import usePageTitle from '../hooks/usePageTitle'
import useActiveSection from '../hooks/useActiveSection'
import usePersistedSet from '../hooks/usePersistedSet'
import { toggleInSet } from '../lib/collections'

function Chevron({ open }) {
  return (
    <svg viewBox="0 0 16 16" fill="none" className={`w-3.5 h-3.5 transition-transform ${open ? 'rotate-90' : ''}`}>
      <path d="M6 4l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// Marks a section whose content was generated by Claude. A blue→red gradient
// robot icon with a matching gradient label, designed to stand out.
const AI_SECTIONS = new Set(['recommendations', 'analysis', 'architecture-changes'])

function AiRobotIcon({ className = 'w-5 h-5' }) {
  const gid = useId()
  return (
    <svg viewBox="0 0 24 24" className={className} aria-hidden="true">
      <defs>
        <linearGradient id={gid} x1="0" y1="0" x2="24" y2="24" gradientUnits="userSpaceOnUse">
          <stop stopColor="#2563eb" />
          <stop offset="1" stopColor="#dc2626" />
        </linearGradient>
      </defs>
      <path d="M12 2.2v2.8" stroke={`url(#${gid})`} strokeWidth="2" strokeLinecap="round" />
      <circle cx="12" cy="2.2" r="1.4" fill={`url(#${gid})`} />
      <rect x="4" y="6" width="16" height="13" fill={`url(#${gid})`} />
      <circle cx="9.2" cy="12" r="1.6" fill="white" />
      <circle cx="14.8" cy="12" r="1.6" fill="white" />
      <rect x="9" y="15.6" width="6" height="1.7" fill="white" />
    </svg>
  )
}

function AiBadge() {
  return (
    <span className="inline-flex items-center gap-1.5 align-middle" title="Generated by Claude AI">
      <AiRobotIcon className="w-5 h-5" />
      <span className="text-[11px] font-bold uppercase tracking-wide bg-gradient-to-r from-blue-600 to-red-600 bg-clip-text text-transparent">
        AI-generated
      </span>
    </span>
  )
}

// ── Status progress bar ───────────────────────────────────────────────────────

const STATUS_STEPS = ['draft', 'proposed', 'accepted', 'staged', 'committed']
const STATUS_TERMINAL = { rejected: 'error' }

const STATUS_TOOLTIPS = {
  draft:     'The decision is being drafted. Not yet submitted for analysis.',
  proposed:  'Submitted for AI analysis. Findings are generated at this stage.',
  accepted:  'Reviewed and accepted. Ready to be staged for application.',
  staged:    'Architecture changes are being applied via a pull request.',
  committed: 'Merged to main. Architecture changes are live.',
  rejected:  'This decision has been rejected and will not proceed.',
}

// Blue → red gradient across the five steps (matches the AI/Claude colourway),
// interpolated from #2563eb to #dc2626.
const STEP_COLORS = ['#2563eb', '#5354ba', '#814589', '#ae3557', '#dc2626']

function StatusProgress({ status }) {
  const isTerminal = status in STATUS_TERMINAL
  const activeStep = STATUS_STEPS.indexOf(status)

  return (
    <div className="mb-8 flex items-center gap-0">
      {STATUS_STEPS.map((step, i) => {
        const isPast = !isTerminal && i < activeStep
        const isCurrent = !isTerminal && i === activeStep
        const reached = isPast || isCurrent

        return (
          <div key={step} className="flex items-center flex-1 last:flex-none">
            <div className="flex flex-col items-center" title={STATUS_TOOLTIPS[step]}>
              <div
                className={`w-7 h-7 flex items-center justify-center text-xs font-semibold cursor-default text-white ${
                  reached ? '' : 'bg-gray-100 !text-gray-400'
                } ${isCurrent ? 'ring-2 ring-offset-1 ring-gray-200' : ''}`}
                style={reached ? { backgroundColor: STEP_COLORS[i] } : undefined}
              >
                {isPast ? <CheckIcon className="w-3.5 h-3.5" /> : i + 1}
              </div>
              <span
                className={`mt-1 text-xs whitespace-nowrap capitalize ${isCurrent ? 'font-semibold' : 'text-gray-400'}`}
                style={isCurrent ? { color: STEP_COLORS[i] } : undefined}
              >
                {step}
              </span>
            </div>
            {i < STATUS_STEPS.length - 1 && (
              <div
                className={`flex-1 h-px mx-2 mb-4 ${i < activeStep && !isTerminal ? '' : 'bg-gray-200'}`}
                style={i < activeStep && !isTerminal ? { backgroundImage: `linear-gradient(to right, ${STEP_COLORS[i]}, ${STEP_COLORS[i + 1]})` } : undefined}
              />
            )}
          </div>
        )
      })}
      {isTerminal && (
        <>
          <div className="h-px w-6 bg-gray-200 mx-2 mb-4" />
          <div className="flex flex-col items-center" title={STATUS_TOOLTIPS.rejected}>
            <div className="w-7 h-7 flex items-center justify-center text-xs font-semibold bg-error-50 text-error-700 ring-2 ring-error-200 cursor-default">!</div>
            <span className="mt-1 text-xs capitalize font-semibold text-error-700">{status}</span>
          </div>
        </>
      )}
    </div>
  )
}

// ── Status transition actions ─────────────────────────────────────────────────

const REJECTION_REASONS = [
  { value: 'duplicate',  label: 'Duplicate — a similar decision already exists or has been accepted' },
  { value: 'superseded', label: 'Superseded — replaced by a newer or broader decision' },
]

function StatusActions({ status, onTransition, transitioning, decision, versionId }) {
  const [rejectOpen, setRejectOpen] = useState(false)
  const [rejectReason, setRejectReason] = useState('duplicate')

  if (status === 'draft') {
    return (
      <div className="mb-6">
        <div className="flex items-center justify-between gap-4 bg-brand-50 px-5 py-4">
          <div>
            <p className="text-sm font-semibold text-brand-900">Ready to propose this decision?</p>
            <p className="text-xs text-brand-600 mt-0.5">Moving to Proposed submits it for analysis and opens a pull request.</p>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <button disabled={transitioning} onClick={() => setRejectOpen(r => !r)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-error-50 border border-error-300 hover:bg-error-100 text-error-700 text-sm font-medium transition-colors disabled:opacity-40">
              Reject
            </button>
            <button disabled={transitioning} onClick={() => onTransition('proposed')}
              className="flex items-center gap-2 px-4 py-1.5 bg-brand-600 hover:bg-brand-700 text-white text-sm font-medium transition-colors disabled:opacity-40">
              {transitioning ? <Spinner size="sm" className="text-white" /> : (
                <>
                  Propose
                  <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
                    <path d="M3 7h8M8 4l3 3-3 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
                  </svg>
                </>
              )}
            </button>
          </div>
        </div>
        {rejectOpen && (
          <div className="bg-error-50 border-t border-error-200 px-5 py-4 flex items-end gap-3">
            <div className="flex-1">
              <label className="block text-xs font-semibold text-error-700 mb-1">Reason for rejection</label>
              <select value={rejectReason} onChange={e => setRejectReason(e.target.value)}
                className="w-full px-3 py-1.5 text-sm border border-error-300 bg-white focus:outline-none">
                {REJECTION_REASONS.map(r => <option key={r.value} value={r.value}>{r.label}</option>)}
              </select>
            </div>
            <button disabled={transitioning}
              onClick={() => { setRejectOpen(false); onTransition('rejected', { 'rejection-reason': rejectReason }) }}
              className="px-4 py-1.5 bg-error-600 hover:bg-error-700 text-white text-sm font-medium transition-colors disabled:opacity-40">
              Confirm Rejection
            </button>
            <button onClick={() => setRejectOpen(false)} className="px-3 py-1.5 text-sm text-gray-500 hover:text-gray-700">Cancel</button>
          </div>
        )}
      </div>
    )
  }

  if (status === 'proposed') {
    return (
      <div className="mb-6">
        <div className="flex items-center justify-between gap-4 bg-success-50 px-5 py-4">
          <div>
            <p className="text-sm font-semibold text-success-700">Accept, reject, or return this decision?</p>
            <p className="text-xs text-success-600 mt-0.5">Accepting approves the change, ready to be staged for application.</p>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <button disabled={transitioning} onClick={() => onTransition('draft')}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-gray-300 hover:bg-gray-50 text-gray-600 text-sm font-medium transition-colors disabled:opacity-40">
              <ArrowLeft className="w-3.5 h-3.5" />
              Back to Draft
            </button>
            <button disabled={transitioning} onClick={() => setRejectOpen(r => !r)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-error-50 border border-error-300 hover:bg-error-100 text-error-700 text-sm font-medium transition-colors disabled:opacity-40">
              Reject
            </button>
            <button disabled={transitioning} onClick={() => onTransition('accepted')}
              className="flex items-center gap-2 px-4 py-1.5 bg-success-500 hover:bg-success-700 text-white text-sm font-medium transition-colors disabled:opacity-40">
              {transitioning ? <Spinner size="sm" className="text-white" /> : (
                <>
                  Accept
                  <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
                    <path d="M2 7l3.5 3.5L12 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
                  </svg>
                </>
              )}
            </button>
          </div>
        </div>
        {rejectOpen && (
          <div className="bg-error-50 border-t border-error-200 px-5 py-4 flex items-end gap-3">
            <div className="flex-1">
              <label className="block text-xs font-semibold text-error-700 mb-1">Reason for rejection</label>
              <select value={rejectReason} onChange={e => setRejectReason(e.target.value)}
                className="w-full px-3 py-1.5 text-sm border border-error-300 bg-white focus:outline-none">
                {REJECTION_REASONS.map(r => <option key={r.value} value={r.value}>{r.label}</option>)}
              </select>
            </div>
            <button disabled={transitioning}
              onClick={() => { setRejectOpen(false); onTransition('rejected', { 'rejection-reason': rejectReason }) }}
              className="px-4 py-1.5 bg-error-600 hover:bg-error-700 text-white text-sm font-medium transition-colors disabled:opacity-40">
              Confirm Rejection
            </button>
            <button onClick={() => setRejectOpen(false)} className="px-3 py-1.5 text-sm text-gray-500 hover:text-gray-700">Cancel</button>
          </div>
        )}
      </div>
    )
  }

  if (status === 'accepted') {
    return (
      <div className="flex items-center justify-between gap-4 bg-emerald-50 px-5 py-4 mb-6">
        <div>
          <p className="text-sm font-semibold text-emerald-800">Stage this decision for application?</p>
          <p className="text-xs text-emerald-600 mt-0.5">Staging applies the artefact changes on the decision branch and opens a pull request for review.</p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <button disabled={transitioning} onClick={() => onTransition('proposed')}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-gray-300 hover:bg-gray-50 text-gray-600 text-sm font-medium transition-colors disabled:opacity-40">
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to Proposed
          </button>
          <button disabled={transitioning} onClick={() => onTransition('staged')}
            className="flex items-center gap-2 px-4 py-1.5 bg-emerald-700 hover:bg-emerald-800 text-white text-sm font-medium transition-colors disabled:opacity-40">
            {transitioning ? <Spinner size="sm" className="text-white" /> : (
              <>
                Stage
                <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
                  <path d="M2 7l3.5 3.5L12 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
                </svg>
              </>
            )}
          </button>
        </div>
      </div>
    )
  }

  if (status === 'staged') {
    return (
      <div className="flex items-center justify-between gap-4 bg-gray-800 px-5 py-4 mb-6">
        <div>
          <p className="text-sm font-semibold text-white">Ready to commit?</p>
          <p className="text-xs text-gray-300 mt-0.5">Committing merges the pull request into main and closes the decision branch.</p>
        </div>
        <button disabled={transitioning} onClick={() => onTransition('committed', { prNumber: decision?.['pr-number'] })}
          className="flex-shrink-0 flex items-center gap-2 px-4 py-1.5 bg-white text-gray-900 text-sm font-semibold hover:bg-gray-100 transition-colors disabled:opacity-40">
          {transitioning ? <Spinner size="sm" className="text-gray-700" /> : (
            <>
              {`Commit to v${versionId}`}
              <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
                <path d="M2 7l3.5 3.5L12 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
              </svg>
            </>
          )}
        </button>
      </div>
    )
  }

  return null
}

// ── Analysis table ────────────────────────────────────────────────────────────

function AnalysisTable({ rows, sectionKey, accepted, onAccept, saving }) {
  if (!rows?.length) return <p className="text-sm text-gray-400">No findings recorded.</p>
  return (
    <div className="border border-gray-200 overflow-x-auto">
      <table className="w-full min-w-[700px] text-sm">
        <thead>
          <tr className="bg-gray-50 border-b border-gray-200">
            {['Finding', 'Impact', 'Recommendation', 'Rationale', ''].map((h, i) => (
              <th key={i} className={`px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide ${i === 4 ? 'w-28' : ''}`}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100">
          {rows.map((row, i) => {
            const key = `${sectionKey}-${i}`
            // Accept/decline state: local overrides first, then JSON field, default to accepted
            const state = accepted[key] ?? row.review ?? 'accepted'
            const isSaving = saving === key
            const isAccepted = state === 'accepted'
            return (
              <tr key={i} className={`align-top ${isAccepted ? 'bg-success-50' : 'bg-error-50'}`}>
                <td className="px-3 py-2.5 text-gray-700 w-1/5">{row.finding ? <Markdown>{row.finding}</Markdown> : '—'}</td>
                <td className="px-3 py-2.5 text-gray-700 w-1/5">{row.impact ? <Markdown>{row.impact}</Markdown> : '—'}</td>
                <td className="px-3 py-2.5 text-gray-700 w-1/5">{row.recommendation ? <Markdown>{row.recommendation}</Markdown> : '—'}</td>
                <td className="px-3 py-2.5 text-gray-700 w-1/5">{row.rationale ? <Markdown>{row.rationale}</Markdown> : '—'}</td>
                <td className="px-3 py-2.5 w-32">
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => onAccept(sectionKey, i, isAccepted ? 'declined' : 'accepted')}
                      disabled={isSaving}
                      className={`relative inline-flex h-5 w-9 flex-shrink-0 items-center transition-colors disabled:opacity-50 focus:outline-none ${isAccepted ? 'bg-success-500' : 'bg-gray-300'}`}
                    >
                      <span className={`inline-block h-4 w-4 bg-white transition-transform ${isAccepted ? 'translate-x-[18px]' : 'translate-x-[2px]'}`} />
                    </button>
                    <span className={`text-xs font-medium whitespace-nowrap ${isAccepted ? 'text-success-700' : 'text-error-700'}`}>
                      {isSaving ? <Spinner size="sm" /> : isAccepted ? 'Accepted' : 'Declined'}
                    </span>
                  </div>
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// ── Recommendations section (narrative-validation output, separate from Analysis) ─

function ReviewSection({ decision }) {
  const items = decision['recommendations']
  if (!items?.length) return null
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
          <CheckIcon className="w-4 h-4 mt-0.5 text-success-600 flex-shrink-0" />
          <Markdown className="min-w-0">{item.recommendation}</Markdown>
        </li>
      ))}
    </ul>
  )
}

// ── Analysis tabs (Untitled UI underline style) ───────────────────────────────

const ANALYSIS_SECTIONS = [
  { key: 'impact-assessment',     label: 'Impact Assessment' },
  { key: 'referential-integrity', label: 'Referential Integrity' },
  { key: 'strategy-alignment',    label: 'Strategy Alignment' },
  { key: 'principles-alignment',  label: 'Principles Alignment' },
  { key: 'guardrails-alignment',  label: 'Guardrails Alignment' },
  { key: 'proponent-analysis',    label: 'Proponent Analysis' },
  { key: 'challenger-analysis',   label: 'Challenger Analysis' },
]

function ArchitectureChanges({ changes }) {
  if (!changes?.length) return null
  return (
    <div className="border border-gray-200 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-200">
              {['Artefact', 'Change', 'Description'].map(h => (
                <th key={h} className="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {changes.map((c, i) => (
              <tr key={i} className="align-top">
                <td className="px-3 py-2.5">
                  <span className="font-mono text-xs bg-gray-100 text-gray-700 px-1.5 py-0.5">{c['artefact-id']}</span>
                  <span className="text-xs text-gray-500 ml-1.5">{c['artefact-name']}</span>
                </td>
                <td className="px-3 py-2.5">
                  <span className={`text-xs font-medium px-2 py-0.5 capitalize ${CHANGE_TYPE_STYLES[c['change-type']] ?? 'bg-gray-100 text-gray-600'}`}>
                    {c['change-type']}
                  </span>
                </td>
                <td className="px-3 py-2.5 text-gray-700">{c.description ? <Markdown>{c.description}</Markdown> : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
    </div>
  )
}

const ANALYSIS_KEYS = ANALYSIS_SECTIONS.map(s => s.key)

// ── History section ───────────────────────────────────────────────────────────

function formatTs(ts) {
  try {
    const d = new Date(ts)
    return d.toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
  } catch { return ts }
}

function HistorySection({ history }) {
  if (!history?.length) return null
  return (
    <div className="border border-gray-200 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-200">
              <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide w-48">Date / Time</th>
              <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide w-32">Event</th>
              <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Notes</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {history.map((entry, i) => (
              <tr key={i} className="align-top">
                <td className="px-4 py-3 text-gray-500 font-mono text-xs whitespace-nowrap">{formatTs(entry.timestamp)}</td>
                <td className="px-4 py-3">
                  <span className={`text-xs font-medium px-2 py-0.5 capitalize ${HISTORY_EVENT_STYLES[entry.event] ?? 'bg-gray-100 text-gray-600'}`}>
                    {entry.event}
                  </span>
                </td>
                <td className="px-4 py-3 text-gray-600 text-xs">{entry.notes || '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
    </div>
  )
}

// ── Contents nav (document-style, left rail) ──────────────────────────────────

function buildNavSections(decision) {
  // Narrative split: Context / Problem / Proposal. Fall back to legacy single
  // narrative for decisions authored before the split.
  const hasSplit = decision.context || decision.problem || decision.proposal
  const narrativeSections = hasSplit
    ? [
        decision.context && { key: 'context', label: 'Context' },
        decision.problem && { key: 'problem', label: 'Problem' },
        decision.proposal && { key: 'proposal', label: 'Proposal' },
      ].filter(Boolean)
    : [{ key: 'narrative', label: 'Narrative' }]

  const analysisTotal = ANALYSIS_SECTIONS.reduce((n, s) => n + (decision[s.key]?.length ?? 0), 0)

  return [
    ...narrativeSections,
    decision.requirements?.length && { key: 'requirements', label: 'Requirements', count: decision.requirements.length },
    decision['recommendations']?.length && { key: 'recommendations', label: 'Recommendations', count: decision['recommendations'].length },
    {
      key: 'analysis',
      label: 'Analysis',
      count: analysisTotal,
      subs: ANALYSIS_SECTIONS.map(s => ({ key: s.key, label: s.label, count: decision[s.key]?.length ?? 0 })),
    },
    decision['architecture-changes']?.length && { key: 'architecture-changes', label: 'Architecture Changes', count: decision['architecture-changes'].length },
    decision.history?.length && { key: 'history', label: 'History', count: decision.history.length },
  ].filter(Boolean)
}

function NavCount({ n, active }) {
  return (
    <span className={`text-xs px-1.5 py-0.5 font-medium tabular-nums flex-shrink-0 ${
      active ? 'bg-rose-100 text-rose-700' : n > 0 ? 'bg-gray-100 text-gray-600' : 'bg-gray-50 text-gray-300'
    }`}>
      {n}
    </span>
  )
}

function ContentsNav({ sections, activeKey, onJump, onExpandAll, onCollapseAll }) {
  return (
    <aside className="hidden lg:block w-64 flex-shrink-0">
      <nav className="sticky top-20 max-h-[calc(100vh-6rem)] overflow-y-auto">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Contents</p>
          <div className="flex items-center gap-2">
            <button onClick={onExpandAll} className="text-xs text-gray-400 hover:text-gray-700 transition-colors">Expand all</button>
            <span className="text-gray-300">·</span>
            <button onClick={onCollapseAll} className="text-xs text-gray-400 hover:text-gray-700 transition-colors">Collapse all</button>
          </div>
        </div>
        <ul className="space-y-0.5">
          {sections.map((s, i) => (
            <li key={s.key}>
              <button
                onClick={() => onJump(s.key)}
                className={`w-full text-left text-sm px-3 py-1.5 transition-colors flex items-center gap-2 border-l-2 ${
                  activeKey === s.key
                    ? 'bg-rose-50 text-rose-700 border-rose-500 font-medium'
                    : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50 border-transparent'
                }`}
              >
                <span className="font-mono text-xs text-gray-400">{i + 1}</span>
                <span className="min-w-0 flex-1 truncate">{s.label}</span>
                {typeof s.count === 'number' && <NavCount n={s.count} active={activeKey === s.key} />}
                {AI_SECTIONS.has(s.key) && <AiRobotIcon className="w-4 h-4 flex-shrink-0" />}
              </button>
              {s.subs && (
                <ul className="mt-0.5 space-y-0.5">
                  {s.subs.map(sub => (
                    <li key={sub.key}>
                      <button
                        onClick={() => onJump(sub.key)}
                        className={`w-full text-left text-xs pl-9 pr-3 py-1 transition-colors flex items-center gap-2 border-l-2 ${
                          activeKey === sub.key
                            ? 'bg-rose-50 text-rose-700 border-rose-500 font-medium'
                            : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50 border-transparent'
                        }`}
                      >
                        <span className="min-w-0 flex-1 truncate">{sub.label}</span>
                        <NavCount n={sub.count} active={activeKey === sub.key} />
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </li>
          ))}
        </ul>
      </nav>
    </aside>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function DecisionDetailPage() {
  const { clientId, versionId, decisionId } = useParams()
  const location = useLocation()
  const { clientsMetadata } = useArchitecture()
  const [decision, setDecision] = useState(undefined)
  const [accepted, setAccepted] = useState({})    // local overrides for finding review state
  const [saving, setSaving] = useState(null)       // key of the finding being saved, e.g. 'impact-assessment-0'
  const [transitioning, setTransitioning] = useState(false)
  const [transitionError, setTransitionError] = useState(null)
  const clientName = clientsMetadata[clientId]?.name ?? clientId

  usePageTitle(decision?.title ? `${decision.title} — Decisions` : 'Decision')

  const sectionRefs = useRef({})
  const [activeSection] = useActiveSection(sectionRefs, [decision])
  const [collapsed, setCollapsed] = usePersistedSet(`decision-collapsed:${clientId}/${versionId}/${decisionId}`)
  const setSectionRef = (key) => (el) => { sectionRefs.current[key] = el }
  const toggleSection = (key) => setCollapsed(prev => toggleInSet(prev, key))
  const scrollToSection = (key) => {
    setCollapsed(prev => {
      const n = new Set(prev)
      n.delete(key)
      // Analysis sub-sections live under the collapsible 'analysis' parent
      if (ANALYSIS_KEYS.includes(key)) n.delete('analysis')
      return n
    })
    requestAnimationFrame(() => requestAnimationFrame(() =>
      sectionRefs.current[key]?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    ))
  }

  // Use branch-then-main fallback via getDecision helper.
  // Bust CDN cache if we just navigated back from the editor after a save.
  useEffect(() => {
    const bust = !!location.state?.cacheBust
    getDecision(clientId, versionId, decisionId, undefined, { bust })
      .then(setDecision)
      .catch(() => setDecision(null))
  }, [clientId, versionId, decisionId])

  async function handleAccept(sectionKey, findingIndex, review) {
    const key = `${sectionKey}-${findingIndex}`
    // Optimistic update
    setAccepted(prev => {
      if (review === null) { const n = { ...prev }; delete n[key]; return n }
      return { ...prev, [key]: review }
    })
    setSaving(key)
    try {
      await fetch('/api/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'update-finding', clientId, versionId, decisionId, sectionKey, findingIndex, review }),
      })
    } catch { /* optimistic — failure leaves local state changed */ }
    finally { setSaving(null) }
  }

  async function handleTransition(newStatus, extraFields = {}) {
    setTransitioning(true)
    setTransitionError(null)
    const updates = { status: newStatus, ...extraFields }
    setDecision(prev => prev ? { ...prev, ...updates } : prev)
    try {
      const action = newStatus === 'committed' ? 'commit-decision' : 'update-decision'
      const body = action === 'commit-decision'
        ? { action, clientId, versionId, decisionId, prNumber: decision?.['pr-number'] }
        : { action, clientId, versionId, decisionId, updates }
      const res = await fetch('/api/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Update failed')
      // Re-fetch busting CDN cache so the new status is immediately visible
      getDecision(clientId, versionId, decisionId, newStatus, { bust: true }).then(setDecision).catch(() => {})
    } catch (err) {
      setTransitionError(err.message)
    } finally {
      setTransitioning(false)
    }
  }

  if (decision === undefined) {
    return <div className="flex items-center justify-center py-20"><Spinner size="lg" /></div>
  }
  if (decision === null) {
    return <Navigate to={`/clients/${clientId}/${versionId}/decisions`} replace />
  }

  const navSections = buildNavSections(decision)
  const sectionNumber = Object.fromEntries(navSections.map((s, i) => [s.key, i + 1]))
  const expandAll = () => setCollapsed(new Set())
  const collapseAll = () => setCollapsed(new Set(navSections.map(s => s.key)))

  const renderSection = (key, children) => {
    const isCollapsed = collapsed.has(key)
    const navItem = navSections.find(s => s.key === key)
    const label = navItem?.label ?? key
    const count = navItem?.count
    return (
      <section ref={setSectionRef(key)} data-section={key} className="scroll-mt-20">
        <button onClick={() => toggleSection(key)} className="w-full flex items-start gap-2 text-left group">
          <span className="text-gray-300 group-hover:text-gray-500 mt-1.5"><Chevron open={!isCollapsed} /></span>
          <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2.5 flex-wrap">
            <span>
              <span className="text-gray-400 font-mono text-base mr-2">{sectionNumber[key]}</span>{label}
            </span>
            {typeof count === 'number' && (
              <span className="text-sm px-1.5 py-0.5 font-medium tabular-nums bg-gray-100 text-gray-600">{count}</span>
            )}
            {AI_SECTIONS.has(key) && <AiBadge />}
          </h2>
        </button>
        {!isCollapsed && <div className="mt-4 ml-6">{children}</div>}
      </section>
    )
  }

  const renderAnalysisSub = (s) => {
    const rows = decision[s.key] ?? []
    return (
      <section key={s.key} ref={setSectionRef(s.key)} data-section={s.key} className="scroll-mt-20">
        <h3 className="text-base font-semibold text-gray-800 flex items-center gap-2 mb-3">
          {s.label}
          <span className="text-xs px-1.5 py-0.5 font-medium tabular-nums bg-gray-100 text-gray-600">{rows.length}</span>
        </h3>
        {rows.length > 0 ? (
          <AnalysisTable rows={rows} sectionKey={s.key} accepted={accepted} onAccept={handleAccept} saving={saving} />
        ) : (
          <div className="border border-dashed border-gray-200 bg-gray-50">
            <EmptyState
              size="sm"
              illustration="findings"
              title="No findings yet"
              description="This section is populated when the analysis workflow runs. Workflows can take a few minutes — check back shortly."
            />
          </div>
        )}
      </section>
    )
  }

  return (
    <div>
      <div className="flex gap-8">
        {/* Contents nav — document-style left rail */}
        <ContentsNav sections={navSections} activeKey={activeSection} onJump={scrollToSection} onExpandAll={expandAll} onCollapseAll={collapseAll} />

        {/* Document surface */}
        <article className="flex-1 min-w-0 bg-white shadow-xl px-8 py-7">
          {/* Header */}
          <div className="mb-6 pb-5 border-b border-gray-200">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-red-600 flex items-center justify-center flex-shrink-0">
                <DecisionIcon className="w-5 h-5 text-white" />
              </div>
              <div className="flex-1 min-w-0">
                <h1 className="text-xl font-semibold text-gray-900">{decision.title}</h1>
                {decision.scope && (
                  <div className="mt-2">
                    <ScopeChip scope={decision.scope} />
                  </div>
                )}
              </div>
              <div className="flex items-center gap-2 flex-shrink-0 self-start">
                <span className="text-xs font-mono bg-gray-100 text-gray-500 px-2 py-1">
                  {decision['decision-id']}
                </span>
                {decision['rejection-reason'] && (
                  <span className="text-xs text-gray-400">{decision['rejection-reason']}</span>
                )}
                {decision.status === 'draft' && (
                  <Link
                    to={`/clients/${clientId}/${versionId}/decisions/${decisionId}/edit`}
                    className="flex items-center gap-1.5 px-3 py-1 bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs font-medium transition-colors"
                  >
                    <svg className="w-3.5 h-3.5" viewBox="0 0 14 14" fill="none">
                      <path d="M9.5 1.5l3 3-8 8H1.5v-3l8-8z" stroke="currentColor" strokeWidth="1.25" strokeLinecap="square" strokeLinejoin="miter" />
                    </svg>
                    Edit
                  </Link>
                )}
              </div>
            </div>
          </div>

          <StatusProgress status={decision.status} />

          {/* Status actions + any error — above the sections */}
          <div className="mb-2">
            <StatusActions status={decision.status} onTransition={handleTransition} transitioning={transitioning} decision={decision} versionId={versionId} />
            {transitionError && (
              <div className="px-4 py-3 bg-error-50 border border-error-300 text-error-700 text-sm">
                Failed to update: {transitionError}
              </div>
            )}
          </div>

          <div className="space-y-8">
            {(decision.context || decision.problem || decision.proposal) ? (
              <>
                {decision.context && renderSection('context',
                  <Markdown className="text-sm text-gray-700 leading-relaxed">{decision.context}</Markdown>
                )}
                {decision.problem && renderSection('problem',
                  <Markdown className="text-sm text-gray-700 leading-relaxed">{decision.problem}</Markdown>
                )}
                {decision.proposal && renderSection('proposal',
                  <Markdown className="text-sm text-gray-700 leading-relaxed">{decision.proposal}</Markdown>
                )}
              </>
            ) : (
              renderSection('narrative',
                <Markdown className="text-sm text-gray-700 leading-relaxed">{decision.narrative}</Markdown>
              )
            )}

            {decision.requirements?.length > 0 && renderSection('requirements',
              <div className="border border-gray-200 divide-y divide-gray-100">
                {decision.requirements.map((req, i) => {
                  const title = typeof req === 'string' ? null : req.title
                  const description = typeof req === 'string' ? req : req.description
                  const type = typeof req === 'object' ? req.type : null
                  return (
                    <div key={i} className="px-4 py-3">
                      <div className="flex items-center gap-2 mb-0.5">
                        {title && <span className="text-sm font-medium text-gray-900">{title}</span>}
                        {type && <span className="text-xs px-1.5 py-0.5 bg-gray-100 text-gray-500">{type}</span>}
                      </div>
                      <Markdown className="text-sm text-gray-600">{description}</Markdown>
                    </div>
                  )
                })}
              </div>
            )}

            {decision['recommendations']?.length > 0 && renderSection('recommendations',
              <ReviewSection decision={decision} />
            )}

            {renderSection('analysis',
              <div className="space-y-8">
                {ANALYSIS_SECTIONS.map(renderAnalysisSub)}
              </div>
            )}

            {decision['architecture-changes']?.length > 0 && renderSection('architecture-changes',
              <ArchitectureChanges changes={decision['architecture-changes']} />
            )}

            {decision.history?.length > 0 && renderSection('history',
              <HistorySection history={decision.history} />
            )}
          </div>

          {/* Status actions — repeated below the sections for convenience */}
          <div className="mt-8">
            <StatusActions status={decision.status} onTransition={handleTransition} transitioning={transitioning} decision={decision} versionId={versionId} />
          </div>

          <ActivityHistory activity={decision.activity} />
        </article>
      </div>

      <JsonPreview data={decision} label={`${decision['decision-id']}.json`} />
    </div>
  )
}
