import { useEffect, useState } from 'react'
import { useParams, Navigate } from 'react-router-dom'
import { useArchitecture } from '../context/ArchitectureContext'
import ScopeChip from '../components/decisions/ScopeChip'
import Markdown from '../components/ui/Markdown'
import Spinner from '../components/ui/Spinner'
import JsonPreview from '../components/ui/JsonPreview'
import ActivityHistory from '../components/common/ActivityHistory'
import Button from '../components/ui/Button'
import ActionBar from '../components/ui/ActionBar'
import AutoGrowTextarea from '../components/ui/AutoGrowTextarea'
import { RobotIcon, EditIcon } from '../components/ui/icons'
import { githubAction } from '../lib/api'
import { formatDate } from '../lib/format'
import usePageTitle from '../hooks/usePageTitle'

const STATUS_BADGE = {
  active: 'bg-emerald-50 text-emerald-700',
  archived: 'bg-gray-100 text-gray-500',
}

// When the point-in-time view was last produced — the most recent activity
// entry (findings are regenerated by the agent, which appends activity).
function discoveredAt(discovery) {
  const ts = discovery.activity?.map((a) => a.timestamp).sort()
  return ts?.length ? ts[ts.length - 1] : null
}

export default function DiscoveryDetailPage() {
  const { clientId, versionId, discoveryId } = useParams()
  const { clientsMetadata } = useArchitecture()
  const [discovery, setDiscovery] = useState(undefined)
  const [archiving, setArchiving] = useState(false)
  const [refreshing, setRefreshing] = useState(false)
  const [edit, setEdit] = useState(null) // { title, context, request } while editing
  const [saving, setSaving] = useState(false)
  const [actionError, setActionError] = useState(null)
  const clientName = clientsMetadata[clientId]?.name ?? clientId
  const canEdit = discovery?.status === 'active'

  usePageTitle(discovery?.title ? `${discovery.title} — Discovery` : 'Discovery')

  useEffect(() => {
    let cancelled = false
    fetch(`/api/arch/clients/${clientId}/${versionId}/discovery/${discoveryId}/discovery.json`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => !cancelled && setDiscovery(d))
      .catch(() => !cancelled && setDiscovery(null))
    return () => {
      cancelled = true
    }
  }, [clientId, versionId, discoveryId])

  async function setStatus(status) {
    const prev = discovery.status
    setArchiving(true)
    setActionError(null)
    setDiscovery((d) => (d ? { ...d, status } : d)) // optimistic
    try {
      await githubAction({
        action: 'update-discovery',
        clientId,
        versionId,
        discoveryId,
        updates: { status },
      })
    } catch (err) {
      setDiscovery((d) => (d ? { ...d, status: prev } : d)) // roll back
      setActionError(`Couldn’t update the discovery: ${err.message}`)
    } finally {
      setArchiving(false)
    }
  }

  async function refresh() {
    setRefreshing(true)
    setActionError(null)
    try {
      await githubAction({ action: 'refresh-discovery', clientId, versionId, discoveryId })
    } catch (err) {
      setRefreshing(false)
      setActionError(`Couldn’t start a refresh: ${err.message}`)
    }
  }

  function startEdit() {
    setEdit({
      title: discovery.title ?? '',
      context: discovery.context ?? '',
      request: discovery.request ?? '',
    })
  }

  // Save inline edits. update-discovery persists the fields and, because the
  // question changed, re-dispatches the to-active workflow to regenerate the
  // point-in-time view — so we show the regenerating banner.
  async function saveEdit() {
    const updates = edit
    const prev = { title: discovery.title, context: discovery.context, request: discovery.request }
    setSaving(true)
    setActionError(null)
    setDiscovery((d) => (d ? { ...d, ...updates } : d)) // optimistic
    try {
      await githubAction({ action: 'update-discovery', clientId, versionId, discoveryId, updates })
      setEdit(null)
      setRefreshing(true)
    } catch (err) {
      setDiscovery((d) => (d ? { ...d, ...prev } : d)) // roll back; keep edit open
      setActionError(`Couldn’t save your changes: ${err.message}`)
    } finally {
      setSaving(false)
    }
  }

  if (discovery === undefined) {
    return (
      <div className="flex items-center justify-center py-20">
        <Spinner size="lg" />
      </div>
    )
  }
  if (discovery === null) {
    return <Navigate to={`/clients/${clientId}/${versionId}/discovery`} replace />
  }

  const Section = ({ title, children }) => (
    <section className="mt-6">
      <h2 className="text-xl font-bold text-gray-900 mb-3">{title}</h2>
      {children}
    </section>
  )

  return (
    <div>
      {edit ? (
        <ActionBar
          className="mb-5"
          tertiary={
            <Button variant="tertiary" onClick={() => setEdit(null)} disabled={saving}>
              Cancel
            </Button>
          }
          primary={
            <Button variant="primary" onClick={saveEdit} disabled={saving || !edit.title.trim()}>
              {saving ? 'Saving…' : 'Save & regenerate'}
            </Button>
          }
        />
      ) : (
        <ActionBar
          className="mb-5"
          tertiary={
            canEdit ? (
              <Button variant="tertiary" onClick={startEdit}>
                <EditIcon className="w-3.5 h-3.5" /> Edit
              </Button>
            ) : undefined
          }
          secondary={
            <Button variant="secondary" onClick={refresh} disabled={refreshing}>
              {refreshing ? 'Refreshing…' : 'Refresh'}
            </Button>
          }
          primary={
            <Button
              variant="secondary"
              onClick={() => setStatus(discovery.status === 'archived' ? 'active' : 'archived')}
              disabled={archiving}
            >
              {archiving ? '…' : discovery.status === 'archived' ? 'Reactivate' : 'Archive'}
            </Button>
          }
        />
      )}

      {actionError && (
        <div className="mb-5 flex items-start gap-3 px-4 py-3 bg-error-50 border border-error-300 text-sm text-error-700">
          <span className="flex-1 min-w-0">{actionError}</span>
          <button
            onClick={() => setActionError(null)}
            className="flex-shrink-0 text-error-400 hover:text-error-700 transition-colors"
            aria-label="Dismiss"
          >
            <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none">
              <path
                d="M4 4l8 8M12 4l-8 8"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
            </svg>
          </button>
        </div>
      )}

      {refreshing && (
        <div className="mb-5 flex items-center gap-3 px-4 py-3 bg-gradient-to-r from-blue-50 to-rose-50 border border-blue-200 text-sm text-gray-700">
          <Spinner size="sm" />
          <span className="flex-1 min-w-0">
            🤖 The Virtual Architect Agent is regenerating this point-in-time view. This usually
            takes a couple of minutes — refresh the page to see the updated findings.
          </span>
        </div>
      )}

      <article className="bg-white shadow-xl px-4 sm:px-8 py-6 sm:py-7">
        <div className="mb-6 pb-5 border-b border-gray-200">
          <div className="flex items-start gap-4">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-red-600 flex items-center justify-center flex-shrink-0">
              <RobotIcon className="w-5 h-5 text-white" />
            </div>
            <div className="flex-1 min-w-0">
              {edit ? (
                <input
                  value={edit.title}
                  onChange={(e) => setEdit((p) => ({ ...p, title: e.target.value }))}
                  aria-label="Discovery title"
                  className="w-full text-xl font-semibold text-gray-900 border-b border-gray-300 focus:border-brand-500 focus:outline-none pb-1"
                />
              ) : (
                <h1 className="text-xl font-semibold text-gray-900">{discovery.title}</h1>
              )}
              <p className="mt-1 text-sm text-gray-500">
                {clientName} · v{versionId}
              </p>
              {discovery.scope && (
                <div className="mt-2">
                  <ScopeChip scope={discovery.scope} />
                </div>
              )}
            </div>
            <div className="flex flex-col items-end gap-2 flex-shrink-0 self-start">
              <div className="flex items-center gap-2">
                <span
                  className={`text-xs font-medium px-2 py-1 capitalize ${STATUS_BADGE[discovery.status] ?? 'bg-gray-100 text-gray-600'}`}
                >
                  {discovery.status}
                </span>
                <span className="text-xs font-mono bg-gray-100 text-gray-500 px-2 py-1">
                  {discovery['discovery-id']}
                </span>
              </div>
              {discoveredAt(discovery) && (
                <span className="inline-flex items-center gap-1.5 text-xs font-medium text-blue-700 bg-blue-50 border border-blue-100 px-2 py-1">
                  <svg className="w-3.5 h-3.5" viewBox="0 0 16 16" fill="none">
                    <rect
                      x="2.5"
                      y="3"
                      width="11"
                      height="10.5"
                      rx="1"
                      stroke="currentColor"
                      strokeWidth="1.25"
                    />
                    <path
                      d="M2.5 6h11M5.5 1.5v3M10.5 1.5v3"
                      stroke="currentColor"
                      strokeWidth="1.25"
                      strokeLinecap="round"
                    />
                  </svg>
                  As at {formatDate(discoveredAt(discovery))}
                </span>
              )}
            </div>
          </div>
        </div>

        <Section title="Context">
          {edit ? (
            <AutoGrowTextarea
              value={edit.context}
              onChange={(e) => setEdit((p) => ({ ...p, context: e.target.value }))}
              minRows={3}
              aria-label="Context"
              className="w-full text-sm text-gray-700 leading-relaxed border border-gray-300 focus:border-brand-500 focus:outline-none px-3 py-2"
            />
          ) : (
            <Markdown className="text-sm text-gray-700 leading-relaxed">
              {discovery.context}
            </Markdown>
          )}
        </Section>

        <Section title="Request">
          {edit ? (
            <AutoGrowTextarea
              value={edit.request}
              onChange={(e) => setEdit((p) => ({ ...p, request: e.target.value }))}
              minRows={3}
              aria-label="Request"
              className="w-full text-sm text-gray-700 leading-relaxed border border-gray-300 focus:border-brand-500 focus:outline-none px-3 py-2"
            />
          ) : (
            <Markdown className="text-sm text-gray-700 leading-relaxed">
              {discovery.request}
            </Markdown>
          )}
        </Section>

        <Section title="Findings">
          {discovery.findings ? (
            <Markdown className="text-sm text-gray-700 leading-relaxed">
              {discovery.findings}
            </Markdown>
          ) : (
            <div className="border border-dashed border-gray-200 bg-gray-50 px-4 py-6 text-center text-sm text-gray-500">
              No findings yet. The Virtual Architect Agent is interrogating the architecture to
              produce a point-in-time view — this takes a couple of minutes. Refresh to check.
            </div>
          )}
        </Section>
      </article>

      {/* Activity sits outside the document surface (no white box / shadow) */}
      <ActivityHistory activity={discovery.activity} />

      <JsonPreview data={discovery} label={`${discovery['discovery-id']}.json`} />
    </div>
  )
}
