on:
  push:
    branches:
      - 'client-**/release-**/adr-**'

permissions:
  contents: read

jobs:
  do-something-with-the-adr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Install CoPilot Extension
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install github/gh-copilot
          gh auth status
          gh copilot explain "sudo apt-get"