on:
  push:
    branches:
      - 'client-**/release-**/adr-**'

permissions:
  contents: read

jobs:
  do-something-with-the-adr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Step 1
        run: |
          echo "something something something"
          echo "something something something"

      - name: Step 2
        run: |
          echo "something something something"
          echo "something something something"