on:
  push:
    branches:
      - 'client-**/release-**/adr-**'

permissions:
  contents: read

jobs:
  do-something-with-the-adr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Step 1
        run: |
          ls -l

      - name: Step 2
        run: |
          echo "something something something" > new-file.txt

      - name: Step 3
        run: |
          ls -l

      - name: Install CoPilot Extension
        run: |
          gh extension install github/gh-copilot

      - name: Make and push changes
        run: |
          gh copilot explain "sudo apt-get"